spring:
  application:
    name: PaymentService
  datasource:
    driver-class-name: org.postgresql.Driver
    password: root
    username: postgres
    url: jdbc:postgresql://localhost/postgres
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8081


