spring:
  application:
    name: CleaningService
  datasource:
    driver-class-name: org.postgresql.Driver
    password: root
    username: postgres
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    consumer:
      group-id: cleaning-service-group
    bootstrap-servers: localhost:9092
server:
  port: 8082

reservation-paid-topic: reservations.events
cleaning-assigned-topic: cleaning.events
